name: Unity Error Check
on:
    workflow_dispatch: {}

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
          lfs: false
      - name: Test
        run: echo "Test"
            
    #   - name: Unity Error Check
    #     run: set -e unity-editor -batchmode -nographics -quit -projectPath . -executeMethod UnityErrorCheck.CheckForErrors
