name: Unity Build
on:
    workflow_dispatch: {}
jobs:
  build:
    # Self-hosted runnerを使用時にはruns-on: self-hostedを指定する    
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false
          lfs: false
      - name: Build
        run: "C:/Users/vantan/Desktop/Runner/unity-build.cmd"
      # - name: Discord Post
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' --data '{"content":"Unity Build Finished"}' ${{ secrets.DISCORD_WEBHOOK_URL }}