name: Unity Build
on:
    workflow_dispatch: {}
jobs:
  build:
    # Self-hosted runnerを使用時にはruns-on: self-hostedを指定する    
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: test.cmd